"""OpenJarvis Artifact Management.

Manages dual persistence for agent artifacts: in-memory state delivery across
neighbor message queues, and disk persistence under `.openjarvis/artifacts/`.
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from openjarvis.workspace import Workspace, discover_workspace


@dataclass
class AgentArtifact:
    """Structured artifact generated by an agent upon milestone or exit."""

    artifact_id: str
    agent_id: str
    name: str
    content: str | dict[str, Any] | list[Any]
    content_type: str = "markdown"  # markdown | code | json | text
    created_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat()
    )
    disk_path: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def text_content(self) -> str:
        """Return the string representation of the artifact content."""
        if isinstance(self.content, str):
            return self.content
        return json.dumps(self.content, indent=2)

    def to_dict(self) -> dict[str, Any]:
        """Convert artifact to serializable dictionary."""
        return asdict(self)


class ArtifactStore:
    """Manages artifact registry and filesystem persistence."""

    def __init__(
        self,
        artifacts_dir: Path | None = None,
        workspace: Workspace | None = None,
    ) -> None:
        if artifacts_dir:
            self.artifacts_dir = Path(artifacts_dir)
        elif workspace:
            self.artifacts_dir = workspace.path("artifacts")
        else:
            ws = discover_workspace()
            self.artifacts_dir = ws.path("artifacts")

        self.artifacts_dir.mkdir(parents=True, exist_ok=True)
        self._artifacts: dict[str, AgentArtifact] = {}

    def _sanitize_filename(self, name: str) -> str:
        """Create a safe filename from an artifact name."""
        clean = re.sub(r"[^\w\-_.]", "_", name.strip())
        return clean or "artifact"

    def _determine_extension(self, content_type: str) -> str:
        """Map content_type to standard file extension."""
        match content_type.lower():
            case "markdown" | "md":
                return ".md"
            case "json":
                return ".json"
            case "python" | "py" | "code":
                return ".py"
            case _:
                return ".txt"

    def save(
        self,
        agent_id: str,
        name: str,
        content: str | dict[str, Any] | list[Any],
        content_type: str = "markdown",
        metadata: dict[str, Any] | None = None,
        artifact_id: str | None = None,
    ) -> AgentArtifact:
        """Create and persist an artifact both in memory and to disk."""
        aid = artifact_id or f"art-{uuid.uuid4().hex[:8]}"
        safe_name = self._sanitize_filename(name)
        ext = self._determine_extension(content_type)
        file_path = self.artifacts_dir / f"{aid}_{safe_name}{ext}"

        artifact = AgentArtifact(
            artifact_id=aid,
            agent_id=agent_id,
            name=name,
            content=content,
            content_type=content_type,
            disk_path=str(file_path),
            metadata=metadata or {},
        )

        # Write to disk
        file_path.write_text(artifact.text_content(), encoding="utf-8")

        # Save in memory
        self._artifacts[aid] = artifact
        return artifact

    def get(self, artifact_id: str) -> AgentArtifact | None:
        """Retrieve an artifact by its ID."""
        return self._artifacts.get(artifact_id)

    def list_for_agent(self, agent_id: str) -> list[AgentArtifact]:
        """Return all artifacts created by a specific agent."""
        return [a for a in self._artifacts.values() if a.agent_id == agent_id]

    def all_artifacts(self) -> list[AgentArtifact]:
        """Return all stored artifacts."""
        return list(self._artifacts.values())
